[package]
name = "unpack_bootimg"
edition = "2021"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
abootimg-oxide.path = ".."
shlex = "1.3.0"
